version: 0.0
os: linux

files:
  - source: /deploy
    destination: /home/ec2-user
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user