spring:
  profiles:
    active: "local"

logging:
  file:
    name: spring-api.log

---

spring:
  config:
    activate:
      on-profile: ["local"]

swagger:
  url: http://localhost:8080
  desc: for local usages

oauth2:
  redirectUri: http://localhost:8080/login/oauth2/code/google
  clientId: 720771356142-qae75m7290099120eqfih689376on2or.apps.googleusercontent.com
  clientSecret: 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
  desc: access token redirect uri for local

---

spring:
  config:
    activate:
      on-profile: ["dev"]

swagger:
  url: http://fairer-dev-env.eba-yzy7enxi.ap-northeast-2.elasticbeanstalk.com/
  desc: for dev usages

oauth2:
  redirectUri: https://ec2-13-125-232-180.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/google
  clientId: 720771356142-qae75m7290099120eqfih689376on2or.apps.googleusercontent.com
  clientSecret: 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
  desc: access token redirect uri for dev

---

spring:
  config:
    activate:
      on-profile: ["local", "dev"]

  datasource:
    url: jdbc:mysql://fairer-database.crfymtbz3gz1.ap-northeast-2.rds.amazonaws.com:3306/fairer_dev
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 'fairer'
    password: '>BRLtas~%j2>(\6#eC2M'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate

  mvc:
    pathmatch:
      # swagger
      matching-strategy: ant_path_matcher

# swagger
springfox:
  documentation:
    enabled: true

  # JWT token
token:
  secret: fairer-backend
  access-token-expiration-time: 99999999999
  refresh-token-expiration-time: 1200000 # 임시 수정(99999999999)

profile:
  domain: https://firebasestorage.googleapis.com/v0/b/fairer-def59.appspot.com/o/
  default-path: fairer-profile-images

---

spring:
  config:
    activate:
      on-profile: "real"

  datasource:
    url: jdbc:mysql://fairer-database.crfymtbz3gz1.ap-northeast-2.rds.amazonaws.com:3306/fairer
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 'fairer'
    password: '>BRLtas~%j2>(\6#eC2M'

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate

  mvc:
    pathmatch:
      # swagger
      matching-strategy: ant_path_matcher

# swagger
springfox:
  documentation:
    enabled: false

swagger:
  url: http://fairer-env.eba-synb99hd.ap-northeast-2.elasticbeanstalk.com:8080
  desc: for real usages

# JWT token
token:
  secret: fairer-backend
  access-token-expiration-time: 900000  # 15분
  refresh-token-expiration-time: 31536000000 # 임시로 1년으로 변경, 안드로이드 갱신 기능 적용 후 2주로 다시 변경

oauth2:
  redirectUri: https://fairer-env.eba-synb99hd.ap-northeast-2.elasticbeanstalk.com/login/oauth2/code/google
  clientId: 720771356142-qae75m7290099120eqfih689376on2or.apps.googleusercontent.com
  clientSecret: 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
  desc: access token redirect uri for real

profile:
  domain: https://firebasestorage.googleapis.com/v0/b/fairer-def59.appspot.com/o/
  default-path: fairer-profile-images
